version: '3.7'
# - All containers have a network configured with the name net_eam_database to create 
# the communication between them.

services:
# --------------------------------------------------------------------
  # - DB refers to the container where the database is stored.
  # - Besides a healthcheck to validate that the MySQL service is up.
  db:
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: example_migrations
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./MySQL/volumes:/var/lib/mysql
    hostname: wms_database
    networks:
      - net_eam_database
    healthcheck:
        test: ["CMD","mysql", "-u", "root", "-proot"]
        interval: 30s
        timeout: 10s
        retries: 5
# --------------------------------------------------------------------
  # - The adminer is a tool for managing content in databases.
  adminer:
    image: adminer
    container_name: adminer_migratios
    restart: always
    ports:
      - 8080:8080
    networks:
      - net_eam_database
# --------------------------------------------------------------------
  # - fastapi refers to the container where the application backend will be stored.
  fastapi:
    build: 
      context: ./FastApi
      dockerfile: Dockerfile
    container_name: fastapi_migrations
    restart: always
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net_eam_database
# --------------------------------------------------------------------

networks:
  net_eam_database:
      driver: bridge
      name: net_eam_database